### ISSUE TITLE
Homework/s

### ISSUE THREAD

**Issue by mariansam** [SoptikHa2/bakalari#1]
Vím, že Bakaláři v modulu pro notifikace používají 'homeworks', ale je nepočitatelné - má být 'homework'.
https://github.com/SoptikHa2/bakalari/blob/master/lib/bakalari.dart#L193 + example

**Comment by SoptikHa2** [comment]
Díky, opraveno ve verzi 0.2.2. Dokonce jsem měl špatně i název jedné metody, takže teď je označená jako Deprecated a ve verzi 0.2.3 ji odstraním.
